---
title: "Exploratory"
author: "Jin Chen"
date: "8/25/2020"
output: html_document
---
```{r}
library(tidyverse)
library(corrplot)
library(countrycode)
library(reshape2)
```

```{r}
#https://www.kaggle.com/unsdsn/world-happiness
wh_2015 <- read.csv("2015.csv") %>% 
  select(Country = Country,
         Rank = Happiness.Rank,
         Score = Happiness.Score,
         Economy = Economy..GDP.per.Capita.,
         Family,
         Health = Health..Life.Expectancy.,
         Freedom,
         GovernmentTrust = Trust..Government.Corruption.,
         Generosity)
wh_2016 <- read.csv("2016.csv") %>% 
  select(Country,
         Rank = Happiness.Rank,
         Score = Happiness.Score,
         Economy = Economy..GDP.per.Capita.,
         Family = Family,
         Health = Health..Life.Expectancy.,
         Freedom = Freedom,
         GovernmentTrust = Trust..Government.Corruption.,
         Generosity)
wh_2017 <- read.csv("2017.csv") %>% 
  select(Country,
         Rank = Happiness.Rank,
         Score = Happiness.Score,
         Economy = Economy..GDP.per.Capita.,
         Family = Family,
         Health = Health..Life.Expectancy.,
         Freedom = Freedom,
         GovernmentTrust = Trust..Government.Corruption.,
         Generosity)
wh_2018 <- read.csv("2018.csv") %>% 
  select(Country = Country.or.region,
         Rank = Overall.rank,
         Score,
         Economy = GDP.per.capita,
         Family = Social.support,
         Health = Healthy.life.expectancy,
         Freedom = Freedom.to.make.life.choices,
         GovernmentTrust = Perceptions.of.corruption,
         Generosity)
wh_2019 <- read.csv("2019.csv") %>% 
    select(Country = Country.or.region,
         Rank = Overall.rank,
         Score,
         Economy = GDP.per.capita,
         Family = Social.support,
         Health = Healthy.life.expectancy,
         Freedom = Freedom.to.make.life.choices,
         GovernmentTrust = Perceptions.of.corruption,
         Generosity)

wh_2015 <- wh_2015 %>% 
  mutate(year = 2015)

wh_2016 <- wh_2016 %>% 
  mutate(year = 2016)

wh_2017 <- wh_2017 %>% 
  mutate(year = 2017)

wh_2018 <- wh_2018 %>% 
  mutate(year = 2018,
         GovernmentTrust = as.numeric(as.character(GovernmentTrust)))

wh_2019 <- wh_2019 %>% 
  mutate(year = 2019)


wh_combined <- bind_rows(wh_2015, wh_2016, wh_2017, wh_2018, wh_2019)

wh_combined %>% 
  select(Country, GovernmentTrust) %>% 
  filter(Country == "United Arab Emirates") %>% 
  summarize(mean = mean(GovernmentTrust, na.rm = TRUE))

wh_combined <- wh_combined %>% 
  group_by(Country) %>% 
  mutate(GovernmentTrust= replace(GovernmentTrust, is.na(GovernmentTrust), mean(GovernmentTrust, na.rm=TRUE)))

wh_combined %>% 
  filter(is.na(GovernmentTrust))



```

```{r}
Num.cols <- sapply(wh_combined, is.numeric)
Cor.data <- cor(wh_combined[c(3:9)])
psych::cor.plot(Cor.data, method = 'color')  
corrplot(Cor.data, method = "color")  
corrplot(Cor.data, method = "number", type = "upper")  
```

```{r}
wh_combined$Region <- countrycode(sourcevar = wh_combined$Country, 
                                  origin = "country.name", 
                                  destination = "region")


wh_combined$Region23 <- countrycode(sourcevar = wh_combined$Country, 
                                  origin = "country.name", 
                                  destination = "region23")
wh_combined %>% 
  filter(is.na(Region23))

wh_combined <- wh_combined %>% 
  group_by(Country) %>% 
  mutate(Region23 = replace(Region23, is.na(Region23), "Southern Europe"))

wh_combined %>% 
  filter(Country == "Kosovo")

#Macedonia changed its name in 2019 to North Macedonia
wh_combined %>% 
  filter(Country == "North Macedonia")

wh_combined <- wh_combined %>% 
  mutate(Country = ifelse(as.character(Country == "Macedonia"), "North Macedonia", as.character(Country))) 

```


```{r}
#graph by region23 for all years
wh_combined %>% 
  group_by(Country, year) %>% 
  ggplot(aes(x = Country, y = Score, color = year)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Region23, scales = "free_y") +
  coord_flip()

#create a df just for 2015 and 2019
wh15_19 <- wh_combined %>% 
  filter(year %in% c(2015, 2019))

#make year a factor
wh15_19 <- wh15_19 %>% 
  mutate(year = as.factor(as.numeric(year)))

#facet wrap by region
wh15_19 %>% 
  group_by(Country) %>% 
  ggplot(aes(x = Country, y = Score, color = year)) +
  geom_line() +
  geom_point() +
  facet_wrap(~Region, scales = "free_y") +
  coord_flip()


#lets just look at one region
wh_SA <- wh_combined %>% 
  filter(Region23 == "South America",
         year %in% c(2015, 2019)) %>% 
  mutate(year = as.factor(as.numeric(year)))

ggplot(wh_SA, aes(x = Country, y = Score, color = year, group = Country)) +
  geom_line() +
  geom_point() +
  coord_flip()

ggplot(wh_SA, aes(x = Country, y = Rank, color = year, group = Country)) +
  geom_line() +
  geom_point() +
  coord_flip()


wh_SA %>% 
  filter(Country == "Suriname")

```




```{r}
Happiness.Region <- wh_combined %>% 
  group_by(Region23) %>% 
  summarize_at(vars(Score:Generosity), mean, na.rm = TRUE)

Happiness.Region.Melt <- melt(Happiness.Region)


ggplot(Happiness.Region.Melt, aes(x = Region23, y = value, color = Region23, fill = Region23)) +
  geom_bar(stat = "identity") +
  facet_wrap(~variable) + theme_bw() +
  theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
  labs(title = "Average value of happiness variables for different continents", 
       y = "Average value") 
```

